server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/bloodneed
spring.data.mongodb.database=bloodneed
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.springframework.data.mongodb=DEBUG